### ISSUE TITLE
dosen't work

### ISSUE THREAD

**Issue by catelina95** [elmoiv/sticker2gif#1]
this url : https://scontent-lax3-1.xx.fbcdn.net/v/t39.1997-6/76179295_953852511743773_4629251374256171426_n.png?_nc_cat=1&_nc_sid=0572db&_nc_ohc=a10LZUWzEMsAX_aALpj&_nc_ht=scontent-lax3-1.xx&oh=81f36d4cc30284b99a83a23646f4da69&oe=5F73726C

can't work

**Comment by elmoiv** [comment]
This was a problem for old versions of Pillow.

The problem was there:
```python
        for i in pics:
            frame = Image.open(opj('temp', i))
            frames.append(frame)
```
Where frame in old versions needs to be copied first, so the code would be like this:
```python
        for i in pics:
            frame = Image.open(opj('temp', i))
            frames.append(frame.copy())
```

I updated the repository, Try it now 😁
